### ISSUE TITLE
How do we select the correct "--extsize" values when we use MACS callpeak

### ISSUE THREAD

**Issue by tpx888** [al-mcintyre/merip_reanalysis_scripts#2]
Hi,

Im a MD candidate of Hebei Medical University. Recently i have been working on some meRIPseq data, when i read your work , i reallized you use macs2 for peak calling ,and use fragment size for "--extsize "  option. 

macs2 callpeak -t alignments/${COND}_IP_${REP}.star.sorted.bam -c alignments/${COND}_input_${REP}.star.sorted.bam --nomodel --extsize **$FRAGLEN** -g 100e6 -n macs2_results/${COND}_${REP}.macs2 -f BAM --verbose 3

Is this the best option for meRIPseq peak calling?  and why we choose fragment size for "--extsize"?

thank you very much!

**Comment by al-mcintyre** [comment]
From [MACS2](https://pypi.org/project/MACS2/): 
"`--extsize`

While --nomodel is set, MACS uses this parameter to extend reads in 5'->3' direction to fix-sized fragments. For example, if the size of the binding region for your transcription factor is 200 bp, and you want to bypass the model building by MACS, this parameter can be set as 200. This option is only valid when --nomodel is set or when MACS fails to build model and --fix-bimodal is on."

MACS2 failed to build a model for the MeRIP-seq data we tested on. We therefore implemented `--extsize` using estimated fragment lengths.

For more details on optimizing MACS2 and peak calling generally, please refer to their documentation and read through my response to another query [here](https://github.com/al-mcintyre/merip_reanalysis_scripts/issues/1).
