### ISSUE TITLE
Re-creating Supplementary Fig. 1f

### ISSUE THREAD

**Issue by pspurg** [al-mcintyre/merip_reanalysis_scripts#3]
Which dataset exactly went into Supplementary Figure 1f (shown below) and is the script available for how it was created?
![image](https://user-images.githubusercontent.com/89164409/129973193-f8cd3552-4b47-4d9c-bafe-53cd4377e94b.png)

**Comment by al-mcintyre** [comment]
Hi, 
The same datasets were used as elsewhere in Figure 1 and Supplementary Figure 1 (mouse cortex on the left and and Huh7 data on the right). Two replicates were selected at random for each. The plot is generated after counting input and IP reads as part of `plot_fig3.R` (lines 134-145), which can be run as Step 6 of `run_full_analysis.sh`.
